### ISSUE TITLE
Local Fallback für jquery

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#12]

**Comment by lukasbesch** [comment]
Hatten wir doch schon:
https://github.com/RawDawg/Kornspeicher/blob/feature-editable-sections/wp-content/themes/kornspeicher/inc/assets.php#L43-L51

Hab aber noch eine bessere Idee, die aber nur in Kombination mit MinQueue Sinn macht. Pushe ich gleich.

**Comment by RawDawg** [comment]
Stimmt! Allerdings war ich gerade kurz offline und jquery wurde nicht geladen … !?
