### ISSUE TITLE
Lightbox: Externe Inhalte, z.B. (Nicht nur) Youtube

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#24]

**Comment by lukasbesch** [comment]
ggf. noch das styling anpassen

**Comment by RawDawg** [comment]
Klappt bei mir nicht … ?
Egal ob ich mit iframe drum oder nur den Link einfüge.

**Comment by lukasbesch** [comment]
Brauchst nur den YouTube-Link einfügen.
Online funktioniert das. (Startseite, klick auf "KORNSPEICHER").
Gibt es eine Fehlermeldung?

**Comment by RawDawg** [comment]
OK, ich hatte dem noch die Popup-Klasse gegeben. Das ist natürlich etwas unflexibel, YT lässt sich ja dann nur als Popup verlinken, selbst wenn man den Haken bei neuer Tab macht. Und wenn man Popup anwählt, was man ja instinktiv tut, geht es gar nicht, ohne Rückmeldung wieso.
