### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#35]

**Comment by lukasbesch** [comment]
Mit dem folgenden Filter funktioniert es, nur lädt er die Seite neu anstatt einen AJAX Request zu machen. Da eh eher Hack als Lösung, eventuell doch eine eigene Lösung?


    // Add body class to sub pages
    add_filter('wpcf7_form_action_url', 'deseng_filter_wpcf7_action_url');
    function deseng_filter_wpcf7_action_url($url) {
	    global $post;
	    $frag = strstr( $url, '#' );
	    $url = get_permalink() . $frag;
	
	    $url = wp_make_link_relative( $url );
	
	    return $url;
    }

**Comment by lukasbesch** [comment]
10ae806ec1fbacd26ea31f05921f0601ae9c06fb
