### ISSUE TITLE
Archiv zeigt Impressum und Popups

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#39]

**Comment by lukasbesch** [comment]
Wo wird das Impressum gezeigt?

**Comment by RawDawg** [comment]
http://www.theofficial.de/preview/kornspeicher/archiv/

Vierter Post

**Comment by lukasbesch** [comment]
09b139444f93c2261064aba5f9c3e28ffbf7ee0c

ACF JSON syncen
