### ISSUE TITLE
PHP im minqueue CSS?

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#42]
Im CSS sind Teile aus der admin-ajax.php, was geht denn da ab!? :-D

**Comment by lukasbesch** [comment]
dayum. Wir sollten auf ein anderes Plugin switchen, wird anscheinend seit WordPress 3.5.2 nicht mehr weiterentwickelt.

**Comment by RawDawg** [comment]
Deaktiviere das mal und schau mal in den Head:
<link rel="stylesheet" id="dynamic-css-css" href="http://localhost:8888/-theOfficial/Kornspeicher/wp-admin/admin-ajax.php" type="text/css" media="all">

Ich vermute, da besteht ein Zusammenhang … ;-)

**Comment by RawDawg** [comment]
Yep, inc/assets.php:

wp_enqueue_style('dynamic-css',
             admin_url('admin-ajax.php') . '?action=deseng_dynamic_css',
             array('kornspeicher')
             );

Brauchen wir das oder kann das weg?

**Comment by lukasbesch** [comment]
müsste damit geschlossen sein:
f61ee382da52c3e0bba4268ea205f14608c8012d
