### ISSUE TITLE
Lightbox: Layoutsprung

### ISSUE THREAD

**Issue by lukasbesch** [RawDawg/Kornspeicher#45]
Je nach Browser/Einstellungen liegen die Scrollbalken nicht über der Webseite, sondern werden daneben dargestellt. Hat eine Webseite Scrollbalken, wird diese dadurch um ca. 15px schmaler.
Wenn eine Lightbox geöffnet wird, wird das globale Scrollen ja deaktiviert. Die Scrollbalken verschwinden dann, dadurch springt die Seite.

Beobachtet in Chrome 44.0.2403.155, OS X 10.10.5

**Comment by RawDawg** [comment]
Ätzend … eigentlich sollte das reichen:
http://jsfiddle.net/XaWZE/

Bei uns aber nicht, die Seite scrollt fröhlich im Hintergrund weiter. Und Safari scheißt bisher auf alles was ich versucht habe.

Alternativ ginge html {overflow-y: visible}
Dann wird das Scrollen auf dem Body verhindert, HTML behält aber den Balken und das Layout springt nicht. Allerdings springt die Seite dann beim Öffnen komplett nach oben.
