### ISSUE TITLE
Druckfunktion

### ISSUE THREAD

**Issue by RawDawg** [RawDawg/Kornspeicher#7]
Wie auch immer …

**Comment by lukasbesch** [comment]
2301d57b750867b1d1c3b61b487541d59cb149d4

 - print button kann man auch direkt ins popup einbinden und natürlich anders stylen
 - wie soll das template aussehen?
 - popupblocker tun das, was sie sollen, benutzer müssen ggf. popups für diese seite aktivieren.

**Comment by RawDawg** [comment]
Überarbeiten: Muss verlässlich funktionieren

**Comment by lukasbesch** [comment]
Bitte mal testen

**Comment by RawDawg** [comment]
Test-Feedback kommt … 
Kann die #fancy_print auch in .fancybox-inner? Das Layout springt sonst beim Laden.

**Comment by lukasbesch** [comment]
Der Button kann überall hin, muss auch nicht per JavaScript nachträglich eingefügt werden. Falls doch, müsste eine andere, frühere Callback-Funktion von FancyBox benutzt werden (ich glaube `beforeShow`).

**Comment by RawDawg** [comment]
Funktioniert jetzt gut bei mir, top!
Vllt packen wir den Button einfach in ein Div mit fester Höhe in .fanybox-inner, dann springt nichts.
